apiVersion: apps/v1
kind: Deployment
metadata:
  name: time
  labels:
    app: time
  namespace: time
  annotations:
    deploymentTime: "2023-03-05T15:46:30Z"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: time
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: time
      namespace: time
    spec:
      containers:
        - image: tercoz/time
          imagePullPolicy: Never
          name: time
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
