apiVersion: apps/v1
kind: Deployment
metadata:
  name: time
  labels:
    app: time
  namespace: time
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: time
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: time
      namespace: time
    spec:
      containers:
      - name: time
        image: tercoz/time
        volumeMounts:
        - name: spring-boot-application-yaml
          mountPath: /srv/application.xml
        imagePullPolicy: Never
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: spring-boot-application-yaml
        configMap:
          name: time
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
