apiVersion: apps/v1
kind: Deployment
metadata:
  name: time
  labels:
    app: time
  namespace: time
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: time
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: time
      namespace: time
    spec:
      containers:
      - name: time
        image: tercoz/time
        volumeMounts:
        - name: application-yml-volume
          mountPath: /srv/application.yml
        - name: logback-xml-volume
          mountPath: /srv/logback.xml
        imagePullPolicy: Never
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: application-yml-volume
        configMap:
          name: time
          items:
            - key: application-yml
              path: application.yml
      - name: logback-xml-volume
        configMap:
          name: time
          items:
            - key: logback-xml
              path: logback.xml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
